<h2>Welcome to Yash's My Module</h2>
<form name="addData" method="post" id="addData" class="form"
              action="<?php echo $this->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>

  <div class="field field-name-firstname required">
     <label class="label" for="firstname">
      <span>First Name</span>
    </label>
    <div class="control">
     <input type="text" id="firstname" name="name" value="" title="name" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
    </div>
  </div>

   <br />
  <!-- <div class="field field-name-lastname required"> 
     <label class="label" for="lastname">
      <span>Last Name</span>
    </label>
    <div class="control">
     <input type="text" id="lastname" name="lname" value="" title="lname" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
    </div>
  </div>
  <br /> -->

  <!-- <div class="field field-name-surname required">
     <label class="label" for="surname">
      <span>surname</span>
    </label>
    <div class="control">
     <input type="text" id="surname" name="surname" value="" title="surname" class="input-text required-entry" data-validate="{required:true}" autocomplete="off" aria-required="true">
    </div>
  </div>
  <br /> -->

  <div class="field field-name-gander required">
   <label for="gender">Gender</label><br>
    <input class="form-check-input" type="radio" name="gender" id="exampleRadios1" value="Male" required>
    <label class="form-check-label" for="exampleRadios1">
    Male
    </label>
    <input class="form-check-input" type="radio" name="gender" id="exampleRadios1" value="Female" required>
    <label class="form-check-label" for="exampleRadios2">
    Female
    </label>
  </div>
  <br />

  <!-- <div class="field required">
    <label for="status" class="label">
     <span>Status</span>
    </label>
    <div class="control">
     <input type="select" name="status" id="status" value="" title="status" class="input-text" data-validate="{required:true}" aria-required="true">
    </div>
  </div> -->
  
  <div class="field required">
    <label for="email_address" class="label">
     <span>Email</span>
    </label>
    <div class="control">
     <input type="email" name="email" autocomplete="email" id="email_address" value="" title="Email" class="input-text" data-validate="{required:true, 'validate-email':true}" aria-required="true">
    </div>
  </div>
  <br />

  <div class="form-group">
    <label for="exampleFormControlTextarea1">What's on your mind?</label>
    <textarea class="form-control" name="feedback" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>
  <div class="actions-toolbar">
    <div class="primary">
    <button type="submit" class="action submit primary" title="Save"><span><?= $block->escapeHtmlAttr(__('Save')) ?></span>
   </button>
   </div>
  </div>
</form>





















<!-- <div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form"
              action="<?php echo $this->getFormAction(); ?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtmlAttr(__('Fill Detail')) ?></span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Name')) ?></span></label>
                            <div class="control">
                                <input name="name" id="name" title="Name" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-alphanum-with-spaces':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->
                                escapeHtmlAttr(__('Email')) ?></span></label>
                            <div class="control">
                                <input name="email" id="email" title="Email" value="" class="input-text" type="text"
                                       data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span><?= $block->escapeHtmlAttr(__('id')) ?></span></label>
                            <div class="control">
                                <input name="id" id="id" title="id" value="" class="input-text"
                                       type="text" data-validate="{required:true}">
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span><?= $block->
                        escapeHtmlAttr(__('Save')) ?></span></button>
                </div>
            </div>
        </form>
    </div>
</div> -->